$script_mysql = <<-SCRIPT
	apt-get update && \
	apt-get install -y mysql-server-5.7 && \
	mysql -e "create user 'phpuser'@'%' identified by 'pass';"
SCRIPT

Vagrant.configure("2") do |config|
	config.vm.box = "hashicorp/bionic64"

	config.vm.define "mysql" do |mysql|
		mysql.vm.network "private_network", ip: "192.168.50.1"

		mysql.vm.provision "shell",
			inline: "cat /vagrant/configs/id_bionic.pub >> .ssh/authorized_keys"
		mysql.vm.provision "shell",
			inline: "cp /vagrant/id_bionic /home/vagrant && \
			        chmod 600 /home/vagrant/id_bionic"
  end

	config.vm.define "phpweb" do |phpweb|
		phpweb.vm.network :forwarded_port, guest: 8888, host: 8089
		phpweb.vm.network "private_network", ip: "192.168.50.2"

		phpweb.vm.provision "shell",
			inline: "apt-get update && apt-get install -y puppet"

		phpweb.vm.provision "puppet" do |puppet|
			puppet.manifests_path = "./configs/manifests"
			puppet.manifest_file = "phpweb.pp"
		end
  end
end
